package com.wadpam.open.dao;

/**
 * Business Methods interface for entity DProfile.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-04-15T09:49:57.282+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DProfileDao extends GeneratedDProfileDao {

	// TODO: declare your Business Methods here
	
}
