package com.wadpam.open.dao;

/**
 * Implementation of Business Methods related to entity DProfile.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-04-15T09:49:57.282+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DProfileDaoBean 
	extends GeneratedDProfileDaoImpl
		implements DProfileDao 
{

	// TODO: implement your Business Methods here

}
