package com.wadpam.open.dao;

/**
 * Implementation of Business Methods related to entity DComplex.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-05T11:25:33.725+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DComplexDaoBean 
	extends GeneratedDComplexDaoImpl
		implements DComplexDao 
{

	// TODO: implement your Business Methods here

}
