package com.wadpam.open.dao;

/**
 * Business Methods interface for entity DSample.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-04T21:26:45.633+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DSampleDao extends GeneratedDSampleDao {

	// TODO: declare your Business Methods here
	
}
