package com.wadpam.open.dao;

/**
 * Business Methods interface for entity DComplex.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-05T11:25:33.725+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DComplexDao extends GeneratedDComplexDao {

	// TODO: declare your Business Methods here
	
}
