package com.wadpam.open.dao;

/**
 * Implementation of Business Methods related to entity DEmployee.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-08T14:16:54.887+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DEmployeeDaoBean 
	extends GeneratedDEmployeeDaoImpl
		implements DEmployeeDao 
{

	// TODO: implement your Business Methods here

}
