package com.wadpam.open.dao;

/**
 * Business Methods interface for entity DOrganization.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-08T14:16:54.887+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DOrganizationDao extends GeneratedDOrganizationDao {

	// TODO: declare your Business Methods here
	
}
