package com.wadpam.open.dao;

/**
 * Implementation of Business Methods related to entity DSample.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-04T21:26:45.633+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DSampleDaoBean 
	extends GeneratedDSampleDaoImpl
		implements DSampleDao 
{

	// TODO: implement your Business Methods here

}
