package com.wadpam.open.push.dao;

import com.wadpam.open.push.domain.DuSubscription;

/**
 * Implementation of Business Methods related to entity DuSubscription.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-04T11:15:21.398+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DuSubscriptionDaoBean 
	extends GeneratedDuSubscriptionDaoImpl
		implements DuSubscriptionDao 
{

    @Override
    public Iterable<DuSubscription> findByDeviceTypeTag(String tag, Long deviceType) {
        
        return queryIterable(false, 0, -1, null, null, null, false, null, false, createEqualsFilter(COLUMN_NAME_TAG, tag),createEqualsFilter(COLUMN_NAME_DEVICETYPE, deviceType));
    }


}
