package com.wadpam.open.push.dao;

/**
 * Implementation of Business Methods related to entity DuSubscription.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-04T11:15:21.398+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DuSubscriptionDaoBean 
	extends GeneratedDuSubscriptionDaoImpl
		implements DuSubscriptionDao 
{

	// TODO: implement your Business Methods here

}
