package com.wadpam.open.push.dao;

import com.wadpam.open.push.domain.DuSubscription;

/**
 * Business Methods interface for entity DuSubscription.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-04T11:15:21.398+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DuSubscriptionDao extends GeneratedDuSubscriptionDao {

	// TODO: declare your Business Methods here
	Iterable<DuSubscription> findByDeviceTypeTag(String tag,Long deviceType);
}
