package com.wadpam.open.dao;

/**
 * Business Methods interface for entity DAppDomain.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-12-26T17:15:59.294+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DAppDomainDao extends GeneratedDAppDomainDao {

}
