package com.wadpam.open.dao;

/**
 * Implementation of Business Methods related to entity DAppDomain.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-12-26T17:15:59.294+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DAppDomainDaoBean 
	extends GeneratedDAppDomainDaoImpl
		implements DAppDomainDao 
{

    // Default constructor to enable caching by Mardao
    public DAppDomainDaoBean() {
        this.memCacheEntities = true;
        this.memCacheAll = false;
    }
}
