package com.wadpam.open.dao;

import com.google.appengine.api.NamespaceManager;
import com.google.appengine.api.datastore.Email;
import com.wadpam.open.domain.DApp;
import net.sf.mardao.core.Filter;

/**
 * Implementation of Business Methods related to entity DApp.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-14T21:35:41.306+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DAppDaoBean 
	extends GeneratedDAppDaoImpl
		implements DAppDao 
{

    // Default constructor to enable caching by Mardao
    public DAppDaoBean() {
        this.memCacheEntities = true;
        this.memCacheAll = true;
    }

    @Override
    // Persist app in a fixed namespace
    public String persist(DApp app) {
        // Preserve current namespace:
        final String currentNamespace = NamespaceManager.get();
        NamespaceManager.set("backoffice");

        String result;
        try {
            result = super.persist(app);
        }
        finally {
            // Revert namespace
            NamespaceManager.set(currentNamespace);
        }
        return result;
    }

    // Delete app from a fixed namespace
    @Override
    public boolean delete(DApp dApp) {
        // Preserve current namespace:
        final String currentNamespace = NamespaceManager.get();
        NamespaceManager.set("backoffice");

        boolean result;
        try {
            result = super.delete(dApp);
        }
        finally {
            // Revert namespace
            NamespaceManager.set(currentNamespace);
        }
        return result;
    }

    // Get app from a fixed namespace
    @Override
    public DApp findByPrimaryKey(String domain) {
        // Preserve current namespace:
        final String currentNamespace = NamespaceManager.get();
        NamespaceManager.set("backoffice");

        DApp dApp = null;
        try {
            dApp = super.findByPrimaryKey(domain);
        }
        finally {
            // Revert namespace
            NamespaceManager.set(currentNamespace);
        }
        return dApp;
    }

    // Get all apps for a specific admin email address
    @Override
    public Iterable<DApp> queryByAdminEmail(Email email) {

        // Preserve current namespace:
        final String currentNamespace = NamespaceManager.get();
        NamespaceManager.set("backoffice");

        Iterable<DApp> dAppIterable = null;
        try {
            final Filter filter = createEqualsFilter(COLUMN_NAME_APPADMINS, email);
            dAppIterable = queryIterable(false, 0, -1, null, null, null, false, null, false, filter);
        } finally {
            // Revert namespace
            NamespaceManager.set(currentNamespace);
        }
        return dAppIterable;
    }
}
