package com.wadpam.open.dao;

/**
 * Implementation of Business Methods related to entity DAppAdmin.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-09T07:48:57.528+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DAppAdminDaoBean 
	extends GeneratedDAppAdminDaoImpl
		implements DAppAdminDao 
{
    // Default constructor to enable caching by Mardao
    public DAppAdminDaoBean() {
        this.memCacheEntities = true;
        this.memCacheAll = true;
    }

}
