package com.wadpam.open.dao;


/**
 * Business Methods interface for entity DAppAdmin.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-09T07:48:57.528+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DAppAdminDao extends GeneratedDAppAdminDao {

}
