package com.wadpam.open.user.dao;

/**
 * Implementation of Business Methods related to entity DOpenUser.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-25T13:34:49.636+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DOpenUserDaoBean
	extends GeneratedDOpenUserDaoImpl
		implements DOpenUserDao
{

	// TODO: implement your Business Methods here

}
