package com.wadpam.open.user.dao;

/**
 * Business Methods interface for entity DOpenUser.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-25T13:34:49.636+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DOpenUserDao extends GeneratedDOpenUserDao {

	// TODO: declare your Business Methods here
	
}
